---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Introduction"
      solveButton: false
    - name: module-02
      label: "Finding the Large File"
      solveButton: false
    - name: module-03
      label: "The Mystery"
      solveButton: false
    - name: module-04
      label: "Confirming with lsof"
      solveButton: false
    - name: module-05
      label: "Resolution"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty

